//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CeD.rc
//
#define IDC_SAVENOEXPORT                3
#define IDC_EXPORTNOSAVE                4
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_CEDTYPE                     129
#define IDR_MOTIONLISTTYPE              130
#define IDC_PAN                         130
#define IDC_INVERSE                     131
#define IDR_EVENTLISTTYPE               131
#define IDC_ROTATE                      147
#define IDR_MOTIONEDIT                  150
#define IDC_ZOOM                        154
#define IDC_MOVEPLANEY                  155
#define IDD_TEST                        156
#define IDC_FACEDIR                     156
#define IDC_MOVEDIR                     157
#define IDB_PROJECTTREE                 168
#define IDD_ANIMCTRL                    169
#define IDR_MED_POPUP                   171
#define IDD_EXPORT_PROGRESS             172
#define IDD_T                           182
#define IDD_CHARACTER_SELECT            183
#define IDD_CAMERA1                     184
#define IDD_MOTIONLIST                  185
#define IDD_EVENTLIST                   186
#define IDR_MOVIE                       189
#define IDD_ACTORLIST                   191
#define IDD_MOVIECTRL                   194
#define IDD_ACTOR_NEW                   195
#define IDB_TAB                         196
#define IDR_MOVIE_POPUP                 197
#define IDD_NUMFRAMES                   198
#define IDD_KEY                         199
#define IDC_ACTOR                       200
#define IDC_KEY                         201
#define IDD_SHOTLIST                    202
#define IDD_MOVIEMERGE                  203
#define IDD_EXPORT_DIALOG               205
#define IDD_MOTION_FLAGS                206
#define IDD_POINTLIST                   207
#define IDD_MOVIEPREVIEW                208
#define IDD_SELECT_MESH                 209
#define IDD_PROJECT_EVENTS              210
#define IDD_ATTACH_EVENT_TO_JOINT       218
#define IDD_MOTION                      219
#define IDD_FILEPATHS                   220
#define IDD_EDIT_LAYER                  222
#define IDD_MOVIE_EXPORT                225
#define IDD_SKIN_SELECT                 226
#define IDD_TRANSITIONVIEWER            227
#define IDR_TRANSITIONVIEW              228
#define IDD_FACEDIR                     230
#define IDD_DIALOG1                     231
#define IDD_EXPORTROTATIONSHELP         234
#define IDD_BIDIRECTIONALBLENDVIEWER    235
#define IDD_DIALOG2                     236
#define IDD_PROPS                       237
#define IDD_PROPDEFS                    238
#define IDD_HELP_PROPDEFS               239
#define IDC_CAMERA_TARGETX              1001
#define IDC_CAMERA_TARGETY              1002
#define IDC_PREVIEW_H                   1002
#define IDC_CAMERA_TARGETZ              1003
#define IDC_CAMERA_LOCKBONE             1004
#define IDC_EVENT_X                     1004
#define IDC_CAMERA_ROTATION             1005
#define IDC_EVENT_XLOCAL                1005
#define IDC_EVENT_Y                     1006
#define IDC_EVENT_Z                     1007
#define IDC_CAMERA_ELEVATION            1008
#define IDC_EVENT_YLOCAL                1008
#define IDC_EVENT_RADIUS                1009
#define IDC_EVENT_FRAME                 1010
#define IDC_EVENT_ZLOCAL                1011
#define IDC_MOTION_LIST                 1012
#define IDC_CAMERA_BONE                 1013
#define IDC_EDIT1                       1014
#define IDC_FRAME                       1014
#define IDC_EVENT_NAME                  1014
#define IDC_WEIGHT1                     1015
#define IDC_FOV                         1016
#define IDC_WEIGHT2                     1016
#define IDC_SPEED                       1017
#define IDC_WEIGHT3                     1017
#define IDC_CHARACTER                   1018
#define IDC_DEFINE4                     1018
#define IDC_WEIGHT4                     1018
#define IDC_DEFINE5                     1019
#define IDC_WEIGHT5                     1019
#define IDC_ANIM_SLIDER                 1020
#define IDC_DEFINE6                     1020
#define IDC_DEFINE7                     1021
#define IDC_DEFINE8                     1022
#define IDC_DEFINE9                     1023
#define IDC_DEFINE10                    1024
#define IDC_FRAME_START                 1025
#define IDC_DEFINE11                    1025
#define IDC_FRAME_END                   1026
#define IDC_DEFINE12                    1026
#define IDC_FRAME_TOTAL                 1027
#define IDC_DEFINE13                    1027
#define IDC_FRAME_SPIN                  1028
#define IDC_DEFINE14                    1028
#define IDC_MOTION_ADD                  1029
#define IDC_DEFINE15                    1029
#define IDC_MOTION_DELETE               1030
#define IDC_DESC4                       1030
#define IDC_EVENT_ADD                   1031
#define IDC_MOTION_FLAGS                1031
#define IDC_DESC5                       1031
#define IDC_EVENT_DELETE                1032
#define IDC_DESC6                       1032
#define IDC_MOTION_IMPORT               1032
#define IDC_PROGRESS                    1033
#define IDC_DESC7                       1033
#define IDC_LIST                        1034
#define IDC_DESC8                       1034
#define IDC_DESC9                       1035
#define IDC_EVENT_LIST                  1036
#define IDC_DESC10                      1036
#define IDC_DESC11                      1037
#define IDC_DESC12                      1038
#define IDC_DESC13                      1039
#define IDC_STATIC_EVENT_X              1040
#define IDC_DESC14                      1040
#define IDC_STATIC_EVENT_Y              1041
#define IDC_DESC15                      1041
#define IDC_STATIC_EVENT_Z              1042
#define IDC_STATIC_EVENT_R              1043
#define IDC_STATIC_EVENT_FRAME          1044
#define IDC_EVENT_BONE                  1045
#define IDC_BUTTON1                     1046
#define IDC_COMBO1                      1047
#define IDC_RESETMOVE                   1047
#define IDC_EXPORT_BROWSE_PC            1047
#define IDC_TARGET                      1048
#define IDC_EXPORT_BROWSE_SDC           1048
#define IDC_EXPORT_BROWSE_XBOX          1048
#define IDC_BONE1                       1048
#define IDC_DELETE                      1049
#define IDC_EXPORT_BROWSE_PS2           1049
#define IDC_BONE2                       1049
#define IDC_ADD                         1050
#define IDC_BONE3                       1050
#define IDC_SELECT_ALL                  1051
#define IDC_EDIT                        1051
#define IDC_BONE4                       1051
#define IDC_DEL                         1052
#define IDC_BONE5                       1052
#define IDC_MOVE_X                      1053
#define IDC_X                           1054
#define IDC_MOVE_Y                      1055
#define IDC_Y                           1056
#define IDC_MOVE_Z                      1057
#define IDC_Z                           1058
#define IDC_VX                          1059
#define IDC_VY                          1060
#define IDC_EXPORT_FILE_PC              1060
#define IDC_DEFINE2                     1060
#define IDC_EDIT_PROJECT_EVENT_DEFAULT_RADIUS 1060
#define IDC_TOTAL                       1061
#define IDC_VZ                          1061
#define IDC_DESC2                       1061
#define IDC_EXPORT_FILE_SDC             1061
#define IDC_EXPORT_FILE_XBOX            1061
#define IDC_SLIDER                      1062
#define IDC_MOVE_VX                     1062
#define IDC_EXPORT_FILE_PS2             1062
#define IDC_SPIN                        1063
#define IDC_MOVE_VY                     1063
#define IDC_MOVE_VZ                     1064
#define IDC_NAME                        1064
#define IDC_CHARACTERS                  1065
#define IDC_SELECT_NONE                 1065
#define IDC_STARTFRAME                  1066
#define IDC_MESHES                      1066
#define IDC_RADIO1                      1067
#define IDC_ENDFRAME                    1067
#define IDC_RADIO2                      1068
#define IDC_RADIO3                      1069
#define IDC_MOTION                      1069
#define IDC_RADIO4                      1070
#define IDC_AUTOLINK                    1070
#define IDC_DISPLAYPATH                 1071
#define IDC_NUMFRAMES                   1071
#define IDC_EVENT                       1072
#define IDC_LINKMOTION                  1073
#define IDC_RX                          1073
#define IDC_LINKCHARACTER               1074
#define IDC_RY                          1074
#define IDC_PROPSELECT                  1074
#define IDC_NOEXPORT                    1075
#define IDC_RZ                          1075
#define IDC_SHOTLIST                    1076
#define IDC_MOVE_RX                     1076
#define IDC_MOVE_RY                     1077
#define IDC_MOVE_RZ                     1078
#define IDC_EYE                         1079
#define IDC_RESETFACE                   1080
#define IDC_SETALL_FACE                 1081
#define IDC_SETALL_MOVE                 1082
#define IDC_SCALE                       1083
#define IDC_DEFINE3                     1083
#define IDC_VISIBLE                     1084
#define IDC_DESC3                       1084
#define IDC_CAMERALOCK                  1085
#define IDC_SYMBOL                      1086
#define IDC_EXPORT_ENABLE_N64           1087
#define IDC_EXPORT_ENABLE_GAMECUBE      1087
#define IDC_EXPORT_ENABLE_PC            1088
#define IDC_EXPORT_FILE_N64             1089
#define IDC_EXPORT_FILE_GAMECUBE        1089
#define IDC_EXPORT_BROWSE_N64           1090
#define IDC_EXPORT_BROWSE_GAMECUBE      1090
#define IDC_EXPORT_FORCE_UPPER          1091
#define IDC_BIT0                        1092
#define IDC_EXPORT_ENABLE_SDC           1092
#define IDC_EXPORT_ENABLE_XBOX          1092
#define IDC_BIT1                        1093
#define IDC_EXPORT_FILE_GLOBAL          1093
#define IDC_BIT2                        1094
#define IDC_EXPORT_BROWSE_GLOBAL        1094
#define IDC_BIT3                        1095
#define IDC_EXPORT_ENABLE_PS2           1095
#define IDC_BIT4                        1096
#define IDC_BIT5                        1097
#define IDC_BIT6                        1098
#define IDC_BIT7                        1099
#define IDC_BIT8                        1100
#define IDC_BIT9                        1101
#define IDC_BIT10                       1102
#define IDC_BIT11                       1103
#define IDC_BIT12                       1104
#define IDC_BIT13                       1105
#define IDC_BIT14                       1106
#define IDC_BIT15                       1107
#define IDC_DEFINE0                     1108
#define IDC_DEFINE1                     1109
#define IDC_DESC0                       1110
#define IDC_EXPORT_COLLISIONBUBBLES     1110
#define IDC_DESC1                       1111
#define IDC_EXPORT_MOTIONFLAGS          1111
#define IDC_TIMEACCURATE                1112
#define IDC_STATIC_X                    1113
#define IDC_STATIC_Y                    1114
#define IDC_STATIC_Z                    1115
#define IDC_STATIC_R                    1116
#define IDC_RADIUS                      1117
#define IDC_BONE                        1118
#define IDC_PREVIEW_W                   1120
#define IDC_PLAY                        1121
#define IDC_LIST_PROJECT_EVENTS         1124
#define IDC_EDIT_PROJECT_EVENT_NAME     1126
#define IDC_BUTTON_PROJECT_INSERT_EVENT 1127
#define IDC_BUTTON_PROJECT_EVENT_DELETE 1128
#define IDC_STATIC_RADIUS               1129
#define IDMYOK                          1130
#define IDC_BUTTON_PROJECT_EVENT_EXPORT_LIST 1131
#define IDC_BUTTON_NEW_PROJECT_EVENT    1132
#define IDC_BUTTON_ADD_CURRENT_EVENT    1133
#define IDC_COMBO_PROJECT_EVENTS        1134
#define IDC_BUTTON_INSERT_EVENT         1135
#define IDC_BUTTON_ATTACH_BONE          1136
#define IDC_COMBO_SELECT_ACTIVE_EVENT_LIST 1137
#define IDC_STATIC_INSERT_NEW_EVENT     1138
#define IDC_STATIC_EVENT_NAME           1139
#define IDC_STATIC_DEFAULT_RADIUS       1140
#define IDC_STATIC_IMPORT_EXPORT        1141
#define IDC_STATIC_EVENT_LIST           1142
#define IDC_STATIC_ATTACHED_BONE        1143
#define IDC_COMBO_ATTACHED_BONE         1144
#define IDC_BUTTON_ATTACH_TO_JOINT      1146
#define IDC_BUTTON_PROJECT_EVENT_IMPORT_LIST 1147
#define IDC_DEFINED_EVENTS_DLG_COMBO_ATTACHED_BONE 1148
#define IDC_CHECK_AUTOCLEAR_FACE_DIR_MOTIONLIST 1149
#define IDC_CHECK_AUTOCLEAR_MOVE_DIR_MOTIONLIST 1150
#define IDC_STATIC_ATTACHED_JOINT_TEXT_EVENTLIST 1151
#define IDC_STATIC_ATTACHED_JOINT_DISPLAY_EVENTLIST 1152
#define IDC_NAMETITLE                   1153
#define IDC_FILETITLE                   1154
#define IDC_FILEPATHNAME                1155
#define IDC_BROWSE                      1156
#define IDC_FILEPATH_REPLACE            1157
#define IDC_BROWSESEARCH                1158
#define IDC_BROWSEREPLACE               1159
#define IDC_RADIO_FROMSTART             1160
#define IDC_RADIO_FROMEND               1161
#define IDC_RADIO_ANYWHERE              1162
#define IDC_FILEPATH_SEARCH             1163
#define IDC_STATIC_EVENT_WORLD          1165
#define IDC_STATIC_EVENT_LOCAL          1166
#define IDC_STATIC_EVENT_DIR            1167
#define IDC_STATIC_EVENT_DIST           1168
#define IDC_EVENT_DIR                   1169
#define IDC_EVENT_DIST                  1170
#define IDC_EVENT_DIRLOCAL              1171
#define IDC_EVENT_DISTLOCAL             1172
#define IDC_BLEND                       1174
#define IDC_RATE                        1175
#define IDC_MIRROR                      1176
#define IDC_EXPORT                      1177
#define IDC_DEFINED_EVENTS_DLG_STATIC_ROTX 1178
#define IDC_DEFINED_EVENTS_DLG_STATIC_ROTY 1179
#define IDC_DEFINED_EVENTS_DLG_STATIC_ROTZ 1180
#define IDC_DEFINED_EVENTS_DLG_BUTTON_FORCEPOSX 1181
#define IDC_DEFINED_EVENTS_DLG_BUTTON_FORCEPOSY 1182
#define IDC_DEFINED_EVENTS_DLG_BUTTON_FORCEPOSZ 1183
#define IDC_DEFINED_EVENTS_DLG_ROTX     1184
#define IDC_DEFINED_EVENTS_DLG_ROTY     1185
#define IDC_DEFINED_EVENTS_DLG_ROTZ     1186
#define IDC_DEFINED_EVENTS_DLG_FORCEPOSX 1187
#define IDC_DEFINED_EVENTS_DLG_FORCEPOSY 1188
#define IDC_DEFINED_EVENTS_DLG_FORCEPOSZ 1189
#define IDC_DEFINED_EVENTS_DLG_STATIC_DISTANCE 1190
#define IDC_DEFINED_EVENTS_DLG_DISTANCE 1191
#define IDC_DEFINED_EVENTS_DLG_BUTTON_RELATIVETOJOINT 1192
#define IDC_DEFINED_EVENTS_DLG_BUTTON_ATTACHED 1195
#define IDC_ACTORLIST_STATIC_LAYER      1196
#define IDC_ACTORLIST_LAYER             1197
#define IDC_LINKEDCHARACTER             1198
#define IDC_BUTTON_ATTACH_BONENOW       1199
#define IDC_ADDLAYER                    1200
#define IDC_DELETELAYER                 1201
#define IDC_LAYER                       1202
#define IDC_VIEWALLLAYERS               1203
#define IDC_EXPORT_FRAMERATE_SET        1204
#define IDC_EXPORT_FRAMERATE            1205
#define IDC_CHARACTER_EXPORTFPS_TITLE   1206
#define IDC_CHARACTER_EXPORTFPS         1207
#define IDC_CHARACTER_EXPORTBITS_TITLE  1208
#define IDC_CHARACTER_EXPORT_BITS       1209
#define IDC_EXPORT_BITS_SET             1210
#define IDC_EXPORT_BITS                 1211
#define IDC_MOTION_EXPORTBITS           1212
#define IDC_MOTION_EXPORTFPS            1213
#define IDC_MOTION_EXPORTBITS_SPIN      1216
#define IDC_MOTION_EXPORTFPS_SPIN       1217
#define IDC_CHARACTER_EXPORTBITS_SPIN   1217
#define IDC_CHARACTER_EXPORTFPS_SPIN    1218
#define IDC_MOTION_EXPORTFPS_BUTTON     1218
#define IDC_MOTION_EXPORTBITS_BUTTON    1219
#define IDC_EXPORT_FRAMESPERBLOCK       1220
#define IDC_SPIN1                       1221
#define IDC_EXPORTLINK                  1223
#define IDC_SPIN2                       1223
#define IDC_AUTOLINKDIR                 1224
#define IDC_SPIN3                       1224
#define IDC_FRAMESPIN                   1225
#define IDC_SPIN4                       1225
#define IDC_EVENT_FRAMESPIN             1226
#define IDC_SPIN5                       1226
#define IDC_SKIN                        1227
#define IDC_TRANSITIONLIST              1228
#define IDC_BLENDFRAMESSPINNER          1229
#define IDC_BLENDFRAMES                 1230
#define IDC_BLENDFRAMESTITLE            1231
#define IDC_ORDERUP                     1232
#define IDC_ORDERDOWN                   1233
#define IDC_ORDERTITLE                  1234
#define IDC_PLAYPAUSE                   1235
#define IDC_RESET                       1236
#define IDC_ENDFRAMETOEND               1237
#define IDC_STARTFRAMESSPINNER          1238
#define IDC_STARTFRAMETITLE             1239
#define IDC_ENDFRAMESSPINNER            1240
#define IDC_ENDFRAMETITLE               1241
#define IDC_CYCLE                       1243
#define IDC_PERCENT0                    1244
#define IDC_PERCENT1                    1245
#define IDC_PERCENT2                    1246
#define IDC_PERCENT3                    1247
#define IDC_PERCENT4                    1248
#define IDC_PERCENT5                    1249
#define IDC_BONE0                       1250
#define IDC_WEIGHT0                     1251
#define IDC_SPIN0                       1252
#define IDC_ADDBONE                     1253
#define IDC_REMOVEBONE                  1254
#define IDC_LOCKTOFACEDIR               1255
#define IDC_EXPORTDATAFILE              1256
#define IDC_EXPORTOPTIONS               1257
#define IDC_EXPORTHEADERFILE            1258
#define IDC_EXPORTTEXTFILE              1259
#define IDC_EXPORTHEADERPATHNAME        1260
#define IDC_QUATBLENDING                1264
#define IDC_EDITANIM                    1265
#define IDC_EXPORTMETHOD_SET            1266
#define IDC_QUATERNION                  1272
#define IDC_WORLDROTS                   1274
#define IDC_ROTATIONMETHODTITLE         1275
#define IDC_EDITMOTION                  1276
#define IDC_QUATW_ON                    1277
#define IDC_CHARACTER_EXPORTQUATW_ON    1280
#define IDC_QUATERNION_ON               1282
#define IDC_EXPORTQUATW_ON              1283
#define IDC_EXPORTDEFAULT               1286
#define IDC_GLOBALROTS                  1287
#define IDC_BONEROTATIONHELP            1288
#define IDC_TRANSLUCENT                 1289
#define IDC_ANIM1                       1290
#define IDC_ANIM1PERCENT                1291
#define IDC_ANIM0PERCENT                1292
#define IDC_ANIM0                       1293
#define IDC_SLIDER1                     1294
#define IDC_SKINSELECT_TITLE            1298
#define IDC_SKINSELECT                  1299
#define IDC_EDITEVENT_ACTIVATE          1300
#define IDC_BUTTON_MOVE_TO_JOINT        1301
#define IDC_ATTACH                      1302
#define IDC_BUTTON_DETACH               1303
#define IDC_DEFINED_EVENTS_DLG_BUTTON_LINKED 1304
#define IDC_INTERP                      1305
#define IDC_EDITDEF                     1306
#define IDC_ACTIVE                      1307
#define IDC_IMPORT                      1309
#define IDC_LINKMOTIONCOMBOTITLE        1310
#define IDC_PROPDEFLIST                 1311
#define IDC_PROPNAME                    1312
#define IDC_EXPORTED                    1314
#define IDC_BONECOMBO                   1315
#define IDC_LINKCHARACTERCOMBO          1316
#define IDC_POSX                        1317
#define IDC_POSY                        1318
#define IDC_POSZ                        1319
#define IDC_ROTX                        1320
#define IDC_ROTY                        1321
#define IDC_ROTZ                        1322
#define IDC_STATICROT                   1323
#define IDC_STATICPOS                   1324
#define IDC_NAMESTATIC                  1325
#define IDC_LINKCHARACTERSTATIC         1326
#define IDC_BONESTATIC                  1327
#define IDC_POSITIONSTATIC              1328
#define IDC_ROTATIONSTATIC              1329
#define IDC_POSXSTATIC                  1330
#define IDC_POSYSTATIC                  1331
#define IDC_POSZSTATIC                  1332
#define IDC_ROTXSTATIC                  1333
#define IDC_ROTYSTATIC                  1334
#define IDC_ROTZSTATIC                  1335
#define IDC_PROPLISTSTATIC              1336
#define IDC_ERRORCOUNT                  1337
#define IDC_ERRORLIST                   1339
#define IDC_LOAD                        1340
#define IDC_FACINGRELATIVE              1341
#define IDC_SCALED                      1342
#define IDC_USELINKEDPOS                1343
#define IDC_USELINKEDROT                1344
#define IDC_BLENDANIM0                  1345
#define IDC_FACINGRELATIVEROT           1345
#define IDC_BLENDANIM1                  1346
#define IDC_MIRRORWITHANIM              1346
#define IDC_BLENDANIM2                  1347
#define IDC_ROTMIRROR                   1347
#define IDC_BLENDANIM3                  1348
#define IDC_BLENDWEIGHT0                1349
#define IDC_BLENDWEIGHT1                1350
#define IDC_BLENDWEIGHT2                1351
#define IDC_BLENDWEIGHT3                1352
#define IDC_BLENDED                     1353
#define IDC_WEIGHTSPIN0                 1354
#define IDC_WEIGHTSPIN1                 1355
#define IDC_WEIGHTSPIN2                 1356
#define IDC_WEIGHTSPIN3                 1357
#define IDC_QUATBLENDINGFORPROPS        1358
#define IDC_HELPBUTTON                  1360
#define IDC_HELPTEXT                    1362
#define IDC_EXTENTION                   1363
#define IDC_EVENTPREFIX                 1364
#define IDC_MOTIONPREFIX                1365
#define IDC_LOADTITLE                   1366
#define IDC_MIRRORED                    1367
#define ID_SELECT                       32771
#define ID_VIEW_CONSTRUCTION_PLANE      32773
#define ID_VIEW_GROUND_PLANE            32774
#define ID_VIEW_MOTIONEDIT              32775
#define ID_VIEW_MOTIONLIST              32776
#define ID_VIEW_EVENTLIST               32777
#define ID_STATE_SELECT                 32778
#define ID_STATE_MOVE                   32779
#define ID_STATE_ROTATE                 32780
#define ID_STATE_ZOOM                   32781
#define ID_STATE_SELECTMOVE             32782
#define ID_STATE_SELECTROTATE           32783
#define ID_ANIM_GOTO_START              32784
#define ID_ANIM_PREVIOUS_FRAME          32785
#define ID_ANIM_NEXT_FRAME              32786
#define ID_ANIM_GOTO_END                32787
#define ID_STATE_DRAG                   32788
#define ID_STATE_PAN                    32789
#define ID_ANIM_PLAY                    32790
#define ID_ZOOM_ALL                     32791
#define ID_STATE_MOVEPLANEY             32792
#define ID_STATE_FACEDIR                32793
#define ID_VIEW_PROJECT                 32794
#define ID_CHARACTER_NEW                32795
#define ID_CHARACTER_IMPORT_SKEL        32798
#define ID_CHARACTER_IMPORT_MOTION      32799
#define ID_CHARACTER_EXPORT             32800
#define IDM_INTERP_FACEDIR              32801
#define ID_FACEDIR_INTERP               32802
#define ID_VIEW_ALL_FACEDIR             32803
#define ID_VIEW_ALL_MOVEDIRS            32804
#define ID_VIEW_ALL_FACEDIRS            32805
#define ID_STATE_MOVEDIR                32806
#define ID_MOVEDIR_INTERP               32807
#define ID_CHARACTER_EXPORTN64          32808
#define ID_CHARACTER_EXPORTPC           32809
#define ID_VIEW_MIRRORED_SKELETON       32810
#define ID_MOVIE_NEW                    32811
#define ID_AXISXZ                       32815
#define ID_AXISX                        32816
#define ID_AXISY                        32817
#define ID_AXISZ                        32818
#define ID_MOVIE_INSERTFRAMES           32821
#define ID_MOVIE_DELETEFAMES            32822
#define ID_ACTOR_INSERTFRAMES           32823
#define ID_ACTOR_COPY                   32825
#define ID_ACTOR_DELETEFRAMES           32826
#define ID_DELETECHARACTER              32827
#define ID_CHARACTER_DELETE             32828
#define ID_MOVIE_EXPORTN64              32829
#define ID_MOVIE_EXPORTPC               32830
#define ID_MOVIE_IMPORT                 32831
#define ID_MOVIE_DELETE                 32832
#define ID_MOVIE_MERGE                  32833
#define ID_MENUITEM32834                32834
#define ID_MESH_NEW                     32835
#define ID_MESH_DELETE                  32836
#define ID_EXPORT_CHARACTER             32837
#define ID_MOVIES_EXPORTMOVIEASASCII    32838
#define ID_EVENTS_DEFINEDEVENTS         32840
#define ID_BUTTON32842                  32842
#define ID_EDIT_FILEPATHS               32843
#define ID_CHARACTER_LOADMOTIONS        32844
#define ID_STATE_EVENT                  32845
#define ID_MOVIE_EXPORTGAMECUBE         32846
#define ID_MOVIE_EXPORTXBOX             32847
#define ID_MOVIE_EXPORTPS2              32848
#define ID_MOVIEVIEW_LAYERSELECT        32851
#define ID_VIEW_COMPRESSED_MOTION       32852
#define ID_VIEW_PRIMARY_MOTION          32853
#define ID_VIEW_MOTION_BLENDED          32854
#define ID_MOVIE_EXPORTALL              32855
#define ID_MOVIE_EXPORTPROPERTIES       32856
#define ID_MOVIE_EXPORT                 32857
#define ID_CHARACTER_IMPORT_SKIN        32859
#define ID_ENABLED3D                    32860
#define ID_ENABLE_D3D                   32861
#define ID_TRANSVIEW                    32864
#define ID_BUTTON32865                  32865
#define ID_BUTTON32866                  32866
#define ID_CHARACTER_FACEDIRRECIPE      32867
#define ID_CHARACTER_SKINS              32868
#define ID_CHARACTER_EXPORTALL          32869
#define ID_BIBLENDVIEW                  32870
#define ID_PROPDEF_DIALOG_BUTTON        32873
#define ID_BUTTON32874                  32874
#define ID_CHARACTER_PROPERTIES         32875

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        241
#define _APS_NEXT_COMMAND_VALUE         32876
#define _APS_NEXT_CONTROL_VALUE         1368
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
